
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BankDb
    username: root
    password: ashen0909

  jpa:
    hibernate:
      ddl-auto: update
properties:
  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8089